version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "5000"
      FLASK_APP: "app_module"
    ports:
      - "5000:5000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test-pwd"
      POSTGRES_DB: "my_db"
    ports:
      - "5433:5432"

