version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "5000"
      FLASK_APP: "app_module"
    ports:
      - "5000:5000"
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"


