version: '3'
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - FLASK_APP=app_module
      - DATABASE_URL=postgresql://postgres:test-pwd@db:5432/my_db
    ports:
      - "5000:8080"

  db:
    image: postgres:latest
    environment: 
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:test-pwd@db/my_db
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test-pwd
    ports:
      - "5433:5432"
